# Data Directory
data_dir = "tpsbench"

# Account Info
miner_private_key   = "8c296482b9b763e8be974058272f377462f2975b94454dabb112de0f135e2064"
bencher_private_key = "8c296482b9b763e8be974058272f377462f2975b94454dabb112de0f135e2064"

# Network Params
consensus_cellbase_maturity = 1 # TODO: Add RPC get_consensus_params
## The listened address of metrics service, outputs in prometheus format.
## Default is empty, which means metrics service would not start.
metrics_url = ""

# Dummy Miner
## - start_miner :: Option<millis>: None will not start dummy miner;
##   Some<millis> starts a dummy miner with block_time = millis.
start_miner = 1000

# Benchmark
## - transaction_type :: "In1Out1" | "In2Out2" | "In3Out3"
## - send_delay :: millisecond
[[benchmarks]]
transaction_type = "In2Out2"
send_delay = 10
[[benchmarks]]
transaction_type = "In2Out2"
send_delay = = 1
