# Data Directory
data_dir = "tpsbench"

# Account Info
bencher_private_key = "8c296482b9b763e8be974058272f377462f2975b94454dabb112de0f135e2064"

# Network Params
## - consensus_cellbase_maturity TODO: Add RPC get_consensus_params
## - confirmation_blocks
consensus_cellbase_maturity = 10
confirmation_blocks = 6

# Dummy Miner
## - private_key
## - block_time :: millisecond
# [miner]

# Benchmark
## - transaction_type :: "In1Out1" | "In2Out2" | "In3Out3"
## - send_delay :: millisecond
[[benchmarks]]
transaction_type = "In2Out2"
send_delay = 10
[[benchmarks]]
transaction_type = "In2Out2"
send_delay = 1
