name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'rc-v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2.1
      - name: Build TPS-Bench
        run: |
          # cd tps-bench && cargo build --release
          # cd target/release
          # tar -czvf tps-bench_${{ env.GIT_TAG_NAME }}_x86_64-unknown-linux-gnu.tar.gz  tps-bench

          mkdir -p target/release
          cd target/release
          echo 1 > tps-bench_${{ env.GIT_TAG_NAME }}_x86_64-unknown-linux-gnu.tar.gz

      - name: Release TPS-Bench
        uses: softprops/action-gh-release@v1
        with:
          files: "target/release/tps-bench_${{ env.GIT_TAG_NAME }}_x86_64-unknown-linux-gnu.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
